shell_integration no-cursor

cursor_blink_interval 0

hide_window_decorations yes
draw_window_borders_for_single_window yes
window_padding_width 8
window_margin_width 0
remember_window_position no
remember_window_size no
confirm_os_window_close 0
initial_window_width 1600
initial_window_height 900
active_border_color #111111
inactive_border_color #111111

font_size 12
font_weight normal
adjust_line_height 0
adjust_column_width 0

text_composition_strategy legacy

# disable terminal bell
enable_audio_bell no
visual_bell_duration 0.0

font_family RobotoMonoNerdFontMono
bold_font auto
italic_font auto
bold_italic_font auto

foreground #D3D7CF
background #000000

# TODO: trying to fix clipboard
clipboard_control read-primary read-clipboard write-clipboard write-primary no_append

# The color table

# The 256 terminal colors. There are 8 basic colors, each color has a dull and
# bright version, for the first 16 colors. You can set the remaining 240 colors
# as color16 to color255.

# color0, color8 (black)
color0 #0C0C0C
color8 #555753

# color1, color9 (red)
color1 #CC0000
color9 #EF2929

# color2, color10 (green)
color2  #4E9A06
color10 #06778D

# color3, color11 (yellow)
color3  #C4A000
color11 #FCE94F

# color4, color12 (blue)
color4  #3465A4
color12 #729FCF

# color5, color13 (magenta)
color5  #75507B
color13 #AD7FA8

# color6, color14 (cyan)
color6  #06989A
color14 #34E2E2

# color7, color15 (white)
color7  #8D908A
color15 #ABABA6


