[ids]

*

[main]


leftalt = layer(controllayer)
leftcontrol = leftalt

capslock = overload(nav, esc)

# line below probably isn't needed if keyboard 60%+ is used
esc = `


[controllayer:C]

h = backspace
j = enter


[nav]

h = left
j = down
k = up
l = right


[global]

macro_timeout = 0
macro_repeat_timeout = 0
macro_sequence_timeout = 0
chord_timeout = 0
chord_hold_timeout = 0
oneshot_timeout = 0
overload_tap_timeout = 0
