[ids]

*

[main]


leftalt = layer(controllayer)
leftcontrol = leftalt

# will produce `esc` if capslock is pressed in less than 50 milliseconds after
# last pressed "non-action key" (i.e. any letter, number or anything else
# except Ctrl, Alt, Capslock and similar) - it allows to quickly exit insert
# mode in vim and continue navigating in normal mode via hjkl
#
# otherwise (if capslock is pressed after 50ms since last "non-action" key)
# will produce `esc` on tap and nav layer on hold (i.e. will behave similar to
# regular "overload()" behavior)
capslock = overloadi(esc, overload(nav, esc), 50)

# line below probably isn't needed if keyboard 60%+ is used
esc = `


[controllayer:C]

h = backspace
j = enter


[nav]

h = left
j = down
k = up
l = right


[global]

macro_timeout = 0
macro_repeat_timeout = 0
macro_sequence_timeout = 0
chord_timeout = 0
chord_hold_timeout = 0
oneshot_timeout = 0
overload_tap_timeout = 0
